title: Divya Poojitha Gundabattula
#logo: /assets/img/headset_circle.png
description: With a professional experience of 1.5+ years , I actively seek for an opportunity in any technical role where I can showcase my skillset and be a part of an esteemed organization’s growth while upbringing and enhancing my technical knowledge and expertise . " Being committed to be a part of technical workforce I actively seek for an opportunity in both fresher and experienced categories . "
#show_downloads: true
theme: jekyll-theme-cayman
